[features]
seeds = false
skip-lint = false
[programs.localnet]
owner_check = "HQYNznB3XTqxzuEqqKMAD9XkYE5BGrnv8xmkoDNcqHYB"
clone = "DUN7nniuatsMC7ReCh5eJRQExnutppN1tAfjfXFmGDq3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/johnliu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
